---
trigger:
  - develop

pool:
  vmImage: 'ubuntu-22.04'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'src/Presentation/Nop.Web/Nop.Web.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
      zipAfterPublish: true
      modifyOutputPath: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/Output
      artifactName: NopOutputs 